#
# This file is part of project link.developers/Student Guide.
# It is copyrighted by the contributors recorded in the version control history of the file,
# available from its original location https://github.com/tuc-nt-df/student-guide.
#
# SPDX-License-Identifier: MPL-2.0
#

site_name: Student Guide

# Repository
repo_url: 'https://github.com/TUC-NT-DF/student-guide'
edit_uri: 'blob/master/docs/'

theme:
  name: material
  logo: assets/logo_white.png
  favicon: assets/favicon.png
  icon:
    repo: fontawesome/brands/github
  palette: 
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
      primary: cyan
      accent: light blue
      
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
      primary: cyan
      accent: light blue
  features:
    - navigation.instant
    - navigation.tracking    
    - navigation.tabs
    - navigation.top
    - search.suggest    
    - content.action.edit
    - toc.integrate 


plugins:
  - search    
  - git-revision-date-localized:  # mamba install mkdocs-git-revision-date-localized-plugin
      enable_creation_date: true

markdown_extensions:
  - markdown.extensions.toc:
      permalink: True
  - markdown.extensions.footnotes
  - markdown.extensions.attr_list

  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - admonition
  - pymdownx.superfences  # for indented code blocks
  - pymdownx.details
  - pymdownx.tabbed
  - pymdownx.arithmatex:
      generic: true
      smart_dollar: true
  - pymdownx.inlinehilite
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.tilde
  - pymdownx.tasklist:
      custom_checkbox: true
extra:
  generator: false  
  
nav:
  - 'Introduction': index.md
  - 'Onboarding':
    - 'Getting Started': content-onboarding/onboarding.md
    - 'HiWi responsibilities': content-onboarding/hiwi.md
    - 'Working with GitHub': content-onboarding/working-with-GitHub.md
    - 'Working with KATA': content-onboarding/KATA.md
    - 'Working with Marvin': content-onboarding/Marvin.md
  - 'Knowledge Base':
    - content-knowledgebase/test_drive.md
    - content-knowledgebase/common_pitfalls.md
    - content-knowledgebase/writing_readme.md
    - content-knowledgebase/linux_hints_for_windows_users.md
    - content-knowledgebase/coordinate-systems.md
  - 'PC3, RFC, Coding guides':
    - content-ops/about-RFCs.md
    - content-ops/PC3.md
    - content-ops/coding-guidelines.md
    - content-ops/how-to-contribute-to-this-guide.md
